runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT rkf.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
  DEBUG: 'False' # always False for deployment

# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  # DB_HOST: '/cloudsql/rkfootwear:asia-south1:rkfootwear-sql'
  # DB_PORT: '3306' # MSQL port
  # DB_NAME: 'RKF'
  # DB_USER: 'rkfootwear-sql' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  # DB_PASSWORD: 'abhi1234'

  # STATIC_URL: 'https://console.cloud.google.com/storage/browser/rkfootwearstatic/static/' # this is the url that you sync static files to

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    secure: always
    # redirect_http_response_code: 301
    script: auto


beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: rkfootwear-v1:asia-south1:rkf-sql

runtime_config:
  python_version: 3.7 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4
