# Generated by Django 2.1.2 on 2020-03-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='return_d',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sale_d',
            new_name='sale_date',
        ),
    ]
