# Generated by Django 3.0.5 on 2020-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0003_auto_20200321_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Open_stock',
            field=models.IntegerField(default='0'),
        ),
    ]
