# Generated by Django 3.0.5 on 2020-05-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0004_items_open_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_qty', models.IntegerField()),
                ('return_dt', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemapp.Items')),
            ],
        ),
    ]
