# Generated by Django 3.0.5 on 2020-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0005_stockaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaudit',
            name='name',
            field=models.CharField(default='Empty', max_length=64),
        ),
    ]
