# Generated by Django 3.0.5 on 2020-05-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0006_stockaudit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockaudit',
            name='name',
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='total_sale',
            field=models.IntegerField(default='0'),
        ),
    ]
