# Generated by Django 3.0.5 on 2020-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0007_auto_20200507_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaudit',
            name='missing_qty',
            field=models.IntegerField(default='0'),
        ),
    ]
