# Generated by Django 3.0.5 on 2020-05-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0008_stockaudit_missing_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockaudit',
            old_name='return_date',
            new_name='stock_audit_date',
        ),
        migrations.RenameField(
            model_name='stockaudit',
            old_name='return_dt',
            new_name='stock_dt',
        ),
    ]
