# Generated by Django 3.0.5 on 2020-05-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0009_auto_20200507_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaudit',
            name='closing_stock',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='opening_stock',
            field=models.IntegerField(default='0'),
        ),
    ]
