# Generated by Django 3.0.5 on 2020-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0011_items_dump_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='shop_name',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
