# Generated by Django 3.0.5 on 2020-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0012_items_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=64)),
                ('shop_dt', models.DateTimeField(auto_now_add=True)),
                ('shop_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
