# Generated by Django 3.0.5 on 2020-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0013_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='shop_name',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='sales',
            name='shop_name',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
