# Generated by Django 3.0.5 on 2020-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0014_auto_20200514_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaudit',
            name='shop_name',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
